user_name_input_textbox = '#user-name'
user_pass_input_textbox = '#password'
login_button = '#login-button'
inventory_container = '#contents_wrapper > #inventory_container'
error_locator = 'h3'
error_message = 'Epic sadface: Username and password do not match any user in this service'
add_button_elements = '.btn_inventory'
item_link = '//button[@id="{id}"]/ancestor::div[@class="inventory_item"]//div[@class="inventory_item_label"]//a'
shopping_cart_link = '.shopping_cart_link'
shopping_cart_items = '.cart_list .cart_item'